version: 0.2

phases:
  pre_build:
    commands:
      - cd my-app
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: ./my-app/build